### ISSUE TITLE
What aliases am I missing?

### ISSUE THREAD

**Issue by vegeta897** [vegeta897/discord-syntax-test#1]
If you know any more aliases that discord uses for languages, please post them here!

For example, `js` = `javascript`

**Comment by kierajreed** [comment]
I believe the full list is available [here](https://highlightjs.readthedocs.io/en/latest/css-classes-reference.html#language-names-and-aliases).

**Comment by vegeta897** [comment]
Thank you very much!

**Comment by vegeta897** [comment]
Instead of copy pasting from this list I implemented parsing of the language source files of highlight.js, which provided some more accurate results.
